/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meercode;
import meercode.ast.*;
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        AbstractSyntaxTree tree = new AbstractSyntaxTree(new Node("+"));
        tree.getHead().left = new Node("+");
        tree.getHead().left.left = new Node("6");
        tree.getHead().left.right = new Node("9");
        tree.getHead().right = new Node("*");
        tree.getHead().right.left = new Node("3");
        tree.getHead().right.right = new Node("7");
        String output = "C:/Users/robin/Desktop/GitStuff/MeerCode/src/main/java/meercode/TestOutput.txt";
        try
        {
            System.out.println("Making reader");
            ASTReader reader = new ASTReader(tree, output);
            reader.readTree();
            
        }
        catch (Exception E)
        {
            System.out.println("IO Exception occured");
        }
    }
}
