/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meercode;
import meercode.ast.*;
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        AbstractSyntaxTree tree = new AbstractSyntaxTree(new Node("NOP", 'f'));
        tree.getHead().left = new Node("while", 'k');
        tree.getHead().left.left = new Node("<", 'c');
        tree.getHead().left.left.left = new Node("x", 'v');
        tree.getHead().left.left.right = new Node("10", 'n');
        tree.getHead().left.right = new Node("NOP", 'f');
        tree.getHead().left.right.left = new Node("=", 'f');
        tree.getHead().left.right.left.left = new Node("x", 'v');
        tree.getHead().left.right.left.right = new Node("+", 'f');
        tree.getHead().left.right.left.right.left = new Node("x", 'x');
        tree.getHead().left.right.left.right.right = new Node("1", 'n');
        tree.getHead().left.right.right = new Node("print", 'f');
        tree.getHead().left.right.right.middle = new Node("x", 'v');
        tree.getHead().right = new Node("return", 'f');
        tree.getHead().right.middle = new Node("x", 'v');
        

        String output = "C:/Users/robin/Desktop/GitStuff/MeerCode/src/main/java/meercode/TestOutput.txt";
        try
        {
            System.out.println("Making reader");
            ASTReader reader = new ASTReader(tree, output);
            reader.readTree();
            
        }
        catch (Exception E)
        {
            System.out.println("IO Exception occured");
        }
    }
}
