/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meercode;
//TODO: Add support for equals method
import meercode.*;
import meercode.ast.*;
public class MeerCode {
    public static void readerTest()
    {
        AbstractSyntaxTree tree = new AbstractSyntaxTree(new Node("NOP", 'f'));
        
        tree.getHead().mLeft = new Node("=", 'f');
        tree.getHead().mLeft.mLeft = new Node("x", 'v');
        tree.getHead().mLeft.mRight = new Node("0", 'n');
        tree.getHead().mRight = new Node("NOP", 'f');
        tree.getHead().mRight.mLeft = new Node("while", 'k');
        tree.getHead().mRight.mLeft.mLeft = new Node("<=", 'c');
        tree.getHead().mRight.mLeft.mLeft.mLeft = new Node("x", 'v');
        tree.getHead().mRight.mLeft.mLeft.mRight = new Node("10", 'n');
        tree.getHead().mRight.mLeft.mRight = new Node("if", 'k');
        tree.getHead().mRight.mLeft.mRight.mLeft = new Node("==", 'c');
        tree.getHead().mRight.mLeft.mRight.mLeft.mLeft = new Node("%", 'f');
        tree.getHead().mRight.mLeft.mRight.mLeft.mLeft.mLeft = new Node("x", 'v');
        tree.getHead().mRight.mLeft.mRight.mLeft.mLeft.mRight = new Node("2", 'n');
        tree.getHead().mRight.mLeft.mRight.mLeft.mRight = new Node("0",'n');
        tree.getHead().mRight.mLeft.mRight.mMiddle = new Node("print", 'f');
        tree.getHead().mRight.mLeft.mRight.mMiddle.mMiddle = new Node("Even", 'n');
        tree.getHead().mRight.mLeft.mRight.mRight = new Node("print", 'f');
        tree.getHead().mRight.mLeft.mRight.mRight.mMiddle = new Node("Odd", 'n');
        tree.getHead().mRight.mRight = new Node("print", 'f');
        tree.getHead().mRight.mRight.mMiddle = new Node("Done", 'n');

        System.out.println(tree.getHead().mFlag);

        String output = "C:/Users/robin/Desktop/GitStuff/MeerCode/src/main/java/meercode/TestOutput.txt";
        try
        {
            System.out.println("Making reader");
            ASTReader reader = new ASTReader(tree, output);
            reader.readTree();
            
        }
        catch (Exception E)
        {
            System.out.println("IO Exception occured");
        }
    }
    public static void main(String[] args)
    {
        
        Compiler.compile();
    }
}
