/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meercode;

import org.junit.Test;
import static org.junit.Assert.*;

public class MeerCodeTest {
    @Test public void testMeerCodeExists() {
        MeerCode classUnderTest = new MeerCode();
        assertNotNull("MeerCode should exist", classUnderTest);
    }
    @Test public void astReaderTest()
    {
        App classToTest = new App();
        classToTest.readerTest();
    }
}
