package meercode.parser;

import java.util.ArrayList;
import java.util.List;
import java.lang.Exception;
// import java.lang.Exception;
import meercode.ast.*;
import meercode.utils.*;
import meercode.parser.*;

public final class Parser {

    private List<List<String>> kTokens;
    private final static List<String> kKeywords = ReservedWords.getReservedWords();
    private final static List<String> kOperators = ReservedWords.getOperators();
    private final static List<String> kComparators = ReservedWords.getComparators();

    /**
     * Our main testing method
     */
    public static void main(String[] args) {
        List<List<String>> tokens = new ArrayList<List<String>>();
        tokens.add(new ArrayList<String>());
        tokens.get(0).add("test 0 0");
        tokens.get(0).add("test 0 1");
        tokens.add(new ArrayList<String>());
        tokens.get(1).add("test 1 0");

        AbstractSyntaxTree ast = Parser.parseTokens(tokens);
    }

    private Parser() {
        // throw new Exception("Error");
    }

    /**
     * Our main Token interpreter
     * Creates a head (NOP) and puts function on left, next line/node/NOP on right
     * @param pTokens The total list of tokens to translate into AST
     * @return The final AST based on all of the tokens given in the parameter
     */
    public static AbstractSyntaxTree parseTokens(List<List<String>> pTokens) {
        AbstractSyntaxTree tree = new AbstractSyntaxTree(new Node("NOP"));

        for (List<String> rows : pTokens) {
            for (String token : rows) {
                if (kKeywords.contains(token))
                {
                    tree.getHead().mLeft = new Node(token);
                }
            }
        }

        for (List<String> row : pTokens) {
            processMeta(row);
        }
        return tree;
    }

    /**
     * Processes a line of code and gives back info on it
     * @param pTokens The line of code in form of list of tokens
     * @return ParserMeta class that contains the info
     */
    private static ParserMeta processMeta(List<String> pTokens) {
        ParserMeta meta;
        String function = pTokens.get(0);
        String upperCaseFunction = function.toUpperCase();

        if (upperCaseFunction.equals("IF")) {
            meta = new ParserMeta(true, 'c');
        }
        else if (upperCaseFunction.equals("REPEATWHILE")) {
            meta = new ParserMeta(true, 'l');
        }
        else if (arrayContainsFromReference(pTokens, kOperators)) // TODO find a faster way to check if pTokens has one or more element from kOperators
        {
            meta = new ParserMeta(false, 'o');
        }
        else if (function.matches("[A-Z]")) {
            meta = new ParserMeta(false, 'a'); // TODO figure out 
        }
        else {
            throw new IllegalArgumentException("SYNTAX ERROR");
        }
        
        return meta;
    }
    private static Node processTokens(List<String> pTokens) {
        
        return null;
    }

    // We have 3 main ast types: operators, conditionals, and functions
    /**
     * 
     * @param pTokens The tokens to process / the operation's expression
     * @return The head of the operation AST generated by the method
     */
    private static Node operatorAST(List<String> pTokens)
    {
        Node currentNode = new Node();

        return null;
    }
    /**
     * 
     * @param pTokens The tokens to process / the conditional expression
     * @return The head of the conditional AST generated by the method
     */
    private static Node conditionalAST(List<String> pTokens)
    {
        Node currentNode = new Node();
        
        return null;
    }
    /**
     * 
     * @param pTokens The tokens to process / the function's expression
     * @return The head of the function AST generated by the method
     */
    private static Node functionAST(List<String> pTokens)
    {
        Node currentNode = new Node();

        return null;
    }
    // /**
    //  * 
    //  * @param pTokens The tokens to process 
    //  * @return The head of the operation AST generated by the method
    //  */
    // private static Node parenthesisGrouping(List<String> pTokens) {


    //     return null;
    // }

    /**
     * @param pCheck The line of code (tokens) to check
     * @param pReference The list of elements to reference
     * @return If the pCheck contains any of pReference's elements
     */
    private static boolean arrayContainsFromReference(List<String> pCheck, List<String> pReference) {
        for (String elem : pCheck) {
            if (pReference.contains(elem)) return true;
        }
        return false;
    }
}
